INSERT INTO series (title, author_id, subgenre_id) VALUES ("Doubledoor:MAN, MYTH, WIZARD", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Happy Thoughts", 2, 2);
INSERT INTO subgenres (name) VALUES ("Hocus Pocus");
INSERT INTO subgenres (name) VALUES ("Horror");
INSERT INTO authors (name) VALUES ("J.K. Rowling");
INSERT INTO authors (name) VALUES ("Stephen King");
INSERT INTO books (title, year, series_id) VALUES ("MAN", 2000, 1);
INSERT INTO books (title, year, series_id) VALUES ("MYTH", 2008, 1);
INSERT INTO books (title, year, series_id) VALUES ("WIZARD", 2016, 1);
INSERT INTO books (title, year, series_id) VALUES ("Pennywise", 2017, 2);
INSERT INTO books (title, year, series_id) VALUES ("Jack Torrance", 1981, 2);
INSERT INTO books (title, year, series_id) VALUES ("Isaac and Malachai ", 1979, 2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Doubledoor", "Expecto Patroneus", "Wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Lily", "James don't", "Wizard", 1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("James", "Snap you freak!", "Wizard", 1, 1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Harry", "Ginny!", "Wizard", 1,1);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Christine", "Vroom Vroom", "Car", 2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Charles Brady", "HISSSS", "Cat-Man", 2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Jack", "Here's Johnny!!", "HUMAN", 2,2);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES ("Isaac", "Malachai!", "HUMAN", 2,2);
INSERT INTO character_books(book_id, character_id) VALUES (1,1);
INSERT INTO character_books(book_id, character_id) VALUES (2,1);
INSERT INTO character_books(book_id, character_id) VALUES (3,1);
INSERT INTO character_books(book_id, character_id) VALUES (1,2);
INSERT INTO character_books(book_id, character_id) VALUES (1,3);
INSERT INTO character_books(book_id, character_id) VALUES (1,4);
INSERT INTO character_books(book_id, character_id) VALUES (2,4);
INSERT INTO character_books(book_id, character_id) VALUES (3,4);
INSERT INTO character_books(book_id, character_id) VALUES (4,5);
INSERT INTO character_books(book_id, character_id) VALUES (4,6);
INSERT INTO character_books(book_id, character_id) VALUES (5,5);
INSERT INTO character_books(book_id, character_id) VALUES (6,5);
INSERT INTO character_books(book_id, character_id) VALUES (4,7);
INSERT INTO character_books(book_id, character_id) VALUES (5,7);
INSERT INTO character_books(book_id, character_id) VALUES (6,7);
INSERT INTO character_books(book_id, character_id) VALUES (6,8);
